name: CI
on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install
        run: yarn install

      - name: Typescript compilation
        run: | 
          npm install -g typescript
          tsc

      - name: prettier-formatting
        run: |
          yarn run prettier-format
          yarn run prettier-check

      - name: test
        run: yarn run test

      - name: Build the docker image
        run: | 
          docker build -t glean/baivab/1 .
          docker save --output glean-baivab-image.docker glean/baivab/1

      - name: Generating artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test coverage
          path: coverage

